const defaults={
siteName:"Shorif Diamond Topup Center BD",ownerName:"Shorif",ownerRole:"Owner & Top-Up Manager",payment:"01781893290",whatsapp:"01781893290",email:"mdshorifms0716733@gmail.com",
badge:"⚡ FAST • TRUSTED • MANUAL TOP-UP",heroTitle:"Free Fire Diamond <span>Top-Up</span>",heroText:"আপনার UID ও Game Code দিয়ে সহজে Diamond Top-Up করুন। বর্তমানে টপ-আপ ম্যানুয়ালি করা হয়।",packagesTitle:"🌟 UID TOPUP LIST 🌟",packagesSubtitle:"🥇 শুধুমাত্র Game Code দিয়ে 🥇",aboutTitle:"আপনার আস্থা আমাদের ❤️",aboutText:"Shorif Diamond Topup Center BD — বর্তমানে ম্যানুয়ালভাবে সহজ Free Fire Top-Up সেবা।",seo:"Shorif Diamond Topup Center BD - Free Fire Diamond Top Up",bg:"#090b13",accent:"#7c5cff",card:"#111522",text:"#f5f7ff",trust:"yes",
packages:[
["0.25$","25 💎","25 Tk"],["0.50$","50 💎","40 Tk"],["1$","115 💎","80 Tk"],["2$","240 💎","160 Tk"],["3$","355 💎","240 Tk"],["4$","480 💎","320 Tk"],["4.25$","505 💎","350 Tk"],["5$","610 💎","400 Tk"],["6$","725 💎","480 Tk"],["7$","850 💎","560 Tk"],["8$","965 💎","640 Tk"],["8.5$","1015 💎","680 Tk"],["9$","1090 💎","720 Tk"],["10$","1240 💎","800 Tk"],["11$","1355 💎","880 Tk"],["12$","1480 💎","960 Tk"],["13$","1595 💎","1040 Tk"],["14$","1720 💎","1120 Tk"],["15$","1850 💎","1200 Tk"],["16$","1965 💎","1270 Tk"],["17$","2090 💎","1360 Tk"],["18$","2205 💎","1440 Tk"],["19$","2330 💎","1520 Tk"],["20$","2530 💎","1600 Tk"],["25$","3140 💎","2000 Tk"],["30$","3770 💎","2400 Tk"],["40$","5060 💎","3200 Tk"],["50$","6300 💎","4000 Tk"],["80$","10120 💎","6,400 Tk"],["Weekly Lite","🎮 UID","50 Tk"],["Weekly","🎮 UID","160 Tk"],["Monthly","🎮 UID","770 Tk"],["Level Up","🎮 UID","420 Tk"]]};
let S=JSON.parse(localStorage.getItem("shorifV2")||"null")||defaults;
const $=id=>document.getElementById(id);
function wa(){return "https://wa.me/88"+S.whatsapp.replace(/\D/g,"")}
function render(){
 document.documentElement.style.setProperty("--bg",S.bg);document.documentElement.style.setProperty("--accent",S.accent);document.documentElement.style.setProperty("--card",S.card);document.documentElement.style.setProperty("--text",S.text);
 $("pageTitle").textContent=S.siteName;$("metaDesc").content=S.seo;$("brandName").textContent=S.siteName.replace(" BD","").slice(0,28);
 $("ownerName").textContent=S.ownerName;$("ownerRole").textContent=S.ownerRole;$("paymentNumber").textContent=S.payment;$("footerPhone").textContent=S.payment;$("footerEmail").textContent=S.email;$("footerName").textContent="💎 "+S.siteName;
 $("heroBadge").textContent=S.badge;$("heroTitle").innerHTML=S.heroTitle;$("heroText").textContent=S.heroText;$("packagesTitle").textContent=S.packagesTitle;$("packagesSubtitle").textContent=S.packagesSubtitle;$("aboutTitle").textContent=S.aboutTitle;$("aboutText").textContent=S.aboutText;
 $("waHero").href=wa();$("waPay").href=wa();$("trust").style.display=S.trust==="yes"?"grid":"none";
 const g=$("packageGrid"),sel=$("packageSelect");g.innerHTML="";sel.innerHTML="";
 S.packages.forEach((p,i)=>{let d=document.createElement("div");d.className="pkg";d.innerHTML=`<b>${p[0]}</b><div class="diam">${p[1]}</div><div class="price">${p[2]}</div>`;g.appendChild(d);let o=document.createElement("option");o.value=i;o.textContent=`${p[0]} — ${p[1]} — ${p[2]}`;sel.appendChild(o)});
}
function fillAdmin(){let m={aSiteName:"siteName",aOwnerName:"ownerName",aOwnerRole:"ownerRole",aPayment:"payment",aWhatsapp:"whatsapp",aEmail:"email",aBadge:"badge",aHeroTitle:"heroTitle",aHeroText:"heroText",aPackagesTitle:"packagesTitle",aPackagesSubtitle:"packagesSubtitle",aAboutTitle:"aboutTitle",aAboutText:"aboutText",aSeo:"seo",aBg:"bg",aAccent:"accent",aCard:"card",aText:"text",aTrust:"trust"};Object.entries(m).forEach(([id,k])=>$(id).value=S[k]);renderEditors()}
function renderEditors(){let e=$("packageEditor");e.innerHTML="";S.packages.forEach((p,i)=>{let r=document.createElement("div");r.className="pkgEdit";r.innerHTML=`<input value="${p[0]}" data-i="${i}" data-k="0"><input value="${p[1]}" data-i="${i}" data-k="1"><input value="${p[2]}" data-i="${i}" data-k="2"><button data-del="${i}">Delete</button>`;e.appendChild(r)});e.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{S.packages.splice(+b.dataset.del,1);renderEditors()})}
render();
$("adminBtn").onclick=()=>$("adminModal").classList.remove("hidden");$("closeAdmin").onclick=()=>$("adminModal").classList.add("hidden");
$("loginBtn").onclick=()=>{if($("adminUser").value==="admin"&&$("adminPass").value==="Shorif@12345"){$("loginView").classList.add("hidden");$("panelView").classList.remove("hidden");fillAdmin()}else alert("ভুল Admin Login")};
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.add("hidden"));$("tab-"+b.dataset.tab).classList.remove("hidden")});
$("addPackage").onclick=()=>{S.packages.push(["New Package","💎","0 Tk"]);renderEditors()};
$("saveAll").onclick=()=>{let m={aSiteName:"siteName",aOwnerName:"ownerName",aOwnerRole:"ownerRole",aPayment:"payment",aWhatsapp:"whatsapp",aEmail:"email",aBadge:"badge",aHeroTitle:"heroTitle",aHeroText:"heroText",aPackagesTitle:"packagesTitle",aPackagesSubtitle:"packagesSubtitle",aAboutTitle:"aboutTitle",aAboutText:"aboutText",aSeo:"seo",aBg:"bg",aAccent:"accent",aCard:"card",aText:"text",aTrust:"trust"};Object.entries(m).forEach(([id,k])=>S[k]=$(id).value);$("packageEditor").querySelectorAll("input[data-i]").forEach(x=>S.packages[+x.dataset.i][+x.dataset.k]=x.value);localStorage.setItem("shorifV2",JSON.stringify(S));render();alert("সব পরিবর্তন Save হয়েছে!")};
$("logoutBtn").onclick=()=>{$("panelView").classList.add("hidden");$("loginView").classList.remove("hidden")};
$("orderForm").onsubmit=e=>{e.preventDefault();let p=S.packages[+$("packageSelect").value];let msg=`Hello ${S.siteName}%0AOrder: ${encodeURIComponent(p.join(" / "))}%0AUID: ${encodeURIComponent($("uid").value)}%0AGame Code: ${encodeURIComponent($("gameCode").value)}%0AName: ${encodeURIComponent($("customerName").value)}%0APhone: ${encodeURIComponent($("customerPhone").value)}`;window.open(wa()+"?text="+msg,"_blank")};
