const {createClient}=supabase; const db=createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY); const $=id=>document.getElementById(id);
let settings={site_name:'Shorif Diamond Topup Center BD',payment_number:'01781893290',nagad_number:'01781893290',whatsapp_number:'01781893290',support_email:'mdshorifms0716733@gmail.com',admin_photo_url:''}; let packages=[];
const fallbackPackages=[['25💎','25 Diamonds','25'],['50💎','50 Diamonds','40'],['115💎','115 Diamonds','80'],['240💎','240 Diamonds','160'],['355💎','355 Diamonds','240'],['480💎','480 Diamonds','320'],['505💎','505 Diamonds','350'],['610💎','610 Diamonds','400'],['725💎','725 Diamonds','480'],['850💎','850 Diamonds','560'],['965💎','965 Diamonds','640'],['1015💎','1015 Diamonds','680'],['1090💎','1090 Diamonds','720'],['1240💎','1240 Diamonds','800'],['1355💎','1355 Diamonds','880'],['1480💎','1480 Diamonds','960'],['1595💎','1595 Diamonds','1040'],['1720💎','1720 Diamonds','1120'],['1850💎','1850 Diamonds','1200'],['1965💎','1965 Diamonds','1270'],['2090💎','2090 Diamonds','1360'],['2205💎','2205 Diamonds','1440'],['2330💎','2330 Diamonds','1520'],['2530💎','2530 Diamonds','1600'],['3140💎','3140 Diamonds','2000'],['3770💎','3770 Diamonds','2400'],['5060💎','5060 Diamonds','3200'],['6300💎','6300 Diamonds','4000'],['10120💎','10120 Diamonds','6400'],['Weekly Lite','Weekly Lite','50'],['Weekly','Weekly','160'],['Monthly','Monthly','770'],['Level Up','Level Up','420']];
function normalizeWa(n){let x=String(n||'').replace(/\D/g,''); if(x.startsWith('0')) x='88'+x; return x;}
function setPhoto(url){if(!url)return; ['introPhoto','heroPhoto','aboutPhoto'].forEach(id=>{if($(id))$(id).src=url+'?v='+Date.now()});}
function renderPackages(){const g=$('packageGrid'),s=$('packageSelect'); g.innerHTML=''; s.innerHTML='<option value="">প্যাকেজ নির্বাচন করুন</option>'; packages.forEach((p,i)=>{const isSub=!String(p.diamonds).toLowerCase().includes('diamond'); const icon=isSub?'🎮':'💎'; const card=document.createElement('div'); card.className='pkg'; card.innerHTML=`<div class="pkgIcon">${icon}</div><b>${esc(p.title)}</b><small>${esc(p.diamonds)}</small><strong>৳${esc(p.price)}</strong><button class="buy" data-i="${i}">Buy Now</button>`; g.appendChild(card); const o=document.createElement('option'); o.value=p.id||i; o.textContent=`${p.title} — ${p.diamonds} — ৳${p.price}`; s.appendChild(o)}); g.querySelectorAll('.buy').forEach(b=>b.onclick=()=>{s.value=packages[+b.dataset.i].id||''; if(!s.value)s.selectedIndex=+b.dataset.i+1; document.querySelector('.orderArea').scrollIntoView({behavior:'smooth'});});}
function esc(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
async function loadSite(){const r=await db.from('site_settings').select('*').eq('id',1).single(); if(!r.error&&r.data){settings={...settings,...r.data}; if(r.data.notice_text){const n=document.querySelector('.noticeBox p b'); if(n)n.textContent=r.data.notice_text;}} const p=await db.from('packages').select('*').eq('active',true).order('sort_order',{ascending:true}).order('title'); packages=!p.error&&p.data?.length?p.data:fallbackPackages.map((x,i)=>({id:'fallback-'+i,title:x[0],diamonds:x[1],price:x[2]})); renderPackages(); $('bkashNumber').textContent=settings.payment_number||'01781893290'; $('nagadNumber').textContent=settings.nagad_number||settings.payment_number||'01781893290'; $('contactBkash').textContent=$('bkashNumber').textContent; $('contactNagad').textContent=$('nagadNumber').textContent; const wa='https://wa.me/'+normalizeWa(settings.whatsapp_number||settings.payment_number); ['heroWa','contactWa'].forEach(id=>{if($(id))$(id).href=wa}); $('contactEmail').href='mailto:'+(settings.support_email||''); $('contactEmail').textContent='✉️ '+(settings.support_email||''); setPhoto(settings.admin_photo_url);}
async function submitOrder(e){e.preventDefault();const uid=$('uid').value.trim(),name=$('customerName').value.trim(),phone=$('customerPhone').value.trim(),trx=$('transactionId').value.trim(),pid=$('packageSelect').value;if(!pid||!uid||!name||!trx){$('orderMsg').innerHTML='<div class="resultBox">⚠️ Package, UID, Player Name ও Transaction ID পূরণ করুন।</div>';return} const p=packages.find(x=>String(x.id)===String(pid))||packages[$('packageSelect').selectedIndex-1]; if(!p||!p.id||String(p.id).startsWith('fallback-')){$('orderMsg').innerHTML='<div class="resultBox">⚠️ Supabase-এ package data সেটআপ করুন, তারপর order দিন।</div>';return} const orderCode='SDTC-'+Math.floor(10000000+Math.random()*90000000); let userId=null; const session=(await db.auth.getSession()).data.session; if(session)userId=session.user.id; const payload={order_code:orderCode,package_id:p.id,uid,game_code:'',customer_name:name,customer_phone:phone,transaction_id:trx,status:'pending'}; if(userId)payload.user_id=userId; const r=await db.from('orders').insert(payload).select('order_code').single(); if(r.error){$('orderMsg').innerHTML='<div class="resultBox">❌ Order হয়নি: '+esc(r.error.message)+'</div>';return} $('orderMsg').innerHTML=`<div class="resultBox">✅ Order সফল হয়েছে!<br>আপনার Order ID: <b>${esc(r.data.order_code)}</b><br><small>এই ID সংরক্ষণ করুন এবং পরে Status Check করুন।</small></div>`; $('orderForm').reset();}
async function track(){const code=$('trackCode').value.trim(); if(!code)return; const r=await db.rpc('track_order',{p_order_code:code}); if(r.error||!r.data?.length){$('trackResult').innerHTML='<div class="resultBox">❌ এই Order ID পাওয়া যায়নি।</div>';return} const o=r.data[0]; $('trackResult').innerHTML=`<div class="resultBox"><b>${esc(o.order_code)}</b><br>Package: ${esc(o.package_title||'')}<br>Diamond: ${esc(o.diamonds||'')}<br>Price: ৳${esc(o.price||'')}<br>Status: <span class="status ${esc(o.status)}">${esc(o.status)}</span><br><small>${new Date(o.created_at).toLocaleString('bn-BD')}</small></div>`;}
document.querySelectorAll('.copyBtn').forEach(b=>b.onclick=async()=>{const text=$(b.dataset.copy).textContent;await navigator.clipboard.writeText(text);b.textContent='✓ Copied';setTimeout(()=>b.textContent='📋 Copy',1200)});
$('orderForm').addEventListener('submit',submitOrder); $('trackBtn').onclick=track; $('menuBtn').onclick=()=>$('mobileMenu').classList.toggle('show'); document.querySelectorAll('#mobileMenu a').forEach(a=>a.onclick=()=>$('mobileMenu').classList.remove('show'));
function closeNotice(){localStorage.setItem('sdtc_notice_seen','1');$('notice').classList.add('hidden')} $('closeNotice').onclick=closeNotice;$('noticeOk').onclick=closeNotice;
(async()=>{setTimeout(()=>$('intro').classList.add('hide'),2300); if(localStorage.getItem('sdtc_notice_seen'))$('notice').classList.add('hidden'); await loadSite();})();
